language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
rvm:
  - 2.7.2
services:
  - postgres
install:
  - bundle install
  - nvm install node --lts
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - gem install bundler
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:reset db:setup db:migrate
script:
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec brakeman
